services:
  catalog-db:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    ports:
      - "5432:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data

volumes:
  catalog_data:
